name: Node.js Package

on: [push]

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  always-auth: true
                  node-version: "16.x"
                  registry-url: https://npm.pkg.github.com
                  scope: "@fuyanlove"

            - name: Install dependencies
              run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            - name: Publish Package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
